AWSTemapleteFormatVersion: '2010-09-09'

resources:
  MyBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-bucket'
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-bucket'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: !Ref Project