name: Create S3 Bucket

on:
  workflow_dispatch:
    inputs:
      S3_BUCKET_NAME:
        required: true
      STACK_NAME:
        required: true
      AWS_REGION:
        required: true
      KMS_ARN:
        required: true

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install boto3
        run: pip install boto3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Run S3 Creation Script
        run: |
          python core/scripts/createBootstrapS3Bucket.py \
            --s3BucketName "${{ inputs.S3_BUCKET_NAME }}" \
            --stackName "${{ inputs.STACK_NAME }}" \
            --AWSRegion "${{ inputs.AWS_REGION }}" \
            --KMSEncryptionKeyARN "${{ inputs.KMS_ARN }}"
